FROM bitnami/spark:latest


USER root

COPY dags/spark_processing.py /opt/apache/spark

# Install Python packages
RUN pip install --no-cache-dir -U pip \
    && pip install --no-cache-dir \
    pandas \
    numpy \
    python-decouple
#COPY ./requirements_spark.txt /
#RUN pip install --upgrade pip
#RUN pip install -r /requirements_spark.txt