FROM bitnami/spark:latest


USER root
COPY ./dags/spark_task/spark_testing_job.py /opt/bitnami/spark/
COPY ./dags/data/A.csv /opt/bitnami/spark/

# Set executable permission on /opt/bitnami/spark/ directory
RUN chmod +x /opt/bitnami/spark/

# Install Python packages
RUN pip install --no-cache-dir -U pip \
    && pip install --no-cache-dir \
    pandas \
    numpy \
    python-decouple

# Switch back to the non-root user
USER 1001